# Generated by Django 6.0.5 on 2026-06-02 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0002_mailing_owner_recipient_owner_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="first_sending",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Начало рассылки"
            ),
        ),
    ]
