# Generated by Django 6.0.5 on 2026-06-02 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0003_alter_mailing_first_sending"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="attemptsending",
            options={
                "ordering": ["time"],
                "permissions": [("can_disabling_mailing", "Can disabling mailing")],
                "verbose_name": "Попытка",
                "verbose_name_plural": "Попытки",
            },
        ),
    ]
