[tool.poetry]
name = "pyproject-toml"
version = "0.1.0"
description = ""
authors = ["None"]
readme = "README.md"
packages = [{include = "pyproject"}]

[tool.poetry.dependencies]
python = "^3.12"
django = "^6.0.5"
dotenv = "^0.9.9"
psycopg2-binary = "^2.9.12"
pillow = "^12.2.0"


[tool.poetry.group.lint.dependencies]
flake8 = "^7.3.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
